import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Belajar Next JS</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.description}>
          <p>
            Wellcome &nbsp;
            <code className={styles.code}>Saddam</code>
          </p>
          <div>
            <a
              href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
            >
              By{' '}
              <Image
                src="/icon2.png"
                alt="Vercel Logo"
                className={styles.vercelLogo}
                width={100}
                height={100}
                priority
              />
            </a>
          </div>
        </div>

        <div className={styles.center}>
          <Image
            className={styles.logo}
            src="/profile.jpg"
            alt="Next.js Logo"
            width={180}
            height={180}
            priority
          />
        </div>

        <div className={styles.grid}>
          <a
            href="https://api.whatsapp.com/send?phone=083195695266"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2>
              WhatsApp <span>-&gt;</span>
            </h2>
            <p>
              Chat Me
            </p>
          </a>

          <a
            href="https://instagram.com/itsmesadam_?igshid=NGExMmI2YTkyZg=="
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2>
              Instagram <span>-&gt;</span>
            </h2>
            <p>
              My Instagram
            </p>
          </a>

          <a
            href="https://www.facebook.com/andhikasaddam.andhikasaddam"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2>
              Facebook <span>-&gt;</span>
            </h2>
            <p>
              My Facebook
            </p>
          </a>

          <a
            href="http://localhost:3000/user/detail"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2>
              My Bio <span>-&gt;</span>
            </h2>
            <p>
              There you go
            </p>
          </a>
        </div>
      </main>
    </>
  )
}
